Feat profile
ricklemos/sabia-appuser pull request #12
Opened 2021-07-10 17:56 UTC by NandaParodi

2021-07-10 18:05 UTC, ricklemos commented on src/app/profile/components/change-password/change-password.component.html
> +        <div class="text3">Senha atual</div>
Nunca se coloca texto solto em uma div. Usa um <p> ou no máximo um <span>

2021-07-10 18:07 UTC, ricklemos commented on src/app/profile/components/change-password/change-password.component.scss
> +
text, text2, text3 não é uma boa prática pra hierarquizar os textos. Tenta descrever melhor o que são os textos

2021-07-10 18:08 UTC, ricklemos commented on src/app/profile/components/change-password/change-password.component.ts
> +  }
Você não ta dando unsubscribe nesses caras.
Lembra de criar um array de unsubscribes, e dar um map(u=> u.unsubscribe) no ngOnDestroy

2021-07-10 18:09 UTC, ricklemos commented on src/app/profile/components/edit-data/edit-data.component.html
> +        <div class="text3">Nome</div>
texto solto em div

2021-07-10 18:10 UTC, ricklemos commented on src/app/profile/components/edit-data/edit-data.component.scss
> +.ds-button {
Terceira vez que você repete esse código. Tem jeito melhor de fazer isso. Se quiser copiar o jeito que é feito no sessions, é uma boa

2021-07-10 18:10 UTC, ricklemos commented on src/app/profile/components/edit-data/edit-data.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
Apaga esse arquivo de testes

2021-07-10 18:11 UTC, ricklemos commented on src/app/profile/components/edit-data/edit-data.component.ts
> +        console.log(data);
Polícia do console log, pode parar por aí bandida!

2021-07-10 18:12 UTC, ricklemos commented on src/app/profile/components/profile-toolbar/profile-toolbar.component.html
> +  <button mat-icon-button (click)="goBack()" fxFlex="10">
Aqui já dá pra usar collact components

2021-07-10 18:12 UTC, ricklemos commented on src/app/profile/components/profile-toolbar/profile-toolbar.component.scss
> +  width: 100vw;
Usa % ou px

2021-07-10 18:12 UTC, ricklemos commented on src/app/profile/components/profile-view/profile-view.component.html
> +        <div class="text3">E-mail</div>
texto solto em div

2021-07-10 18:13 UTC, ricklemos commented on src/app/profile/components/profile-view/profile-view.component.scss
> +
Tem coisa nesse scss que você nem ta usando

2021-07-10 18:13 UTC, ricklemos commented on src/app/profile/components/profile-view/profile-view.component.ts
> +    ).subscribe(noop);
unsubscribe nesse cara

2021-07-10 18:14 UTC, ricklemos commented on src/app/profile/containers/change-password-page/change-password-page.component.html
> +  <profile-toolbar [pageName]="'Trocar Senha'"></profile-toolbar>
Se você ta passando um string, não precisa fazer data binding. Pode passar assim:
`<profile-toolbar pageName="Trocar Senha"></profile-toolbar>`

2021-07-10 18:14 UTC, ricklemos commented on src/app/profile/containers/change-password-page/change-password-page.component.scss
> +  height: 100vh;
% ou px

2021-07-10 18:15 UTC, ricklemos commented on src/app/profile/containers/profile-edit-page/profile-edit-page.component.html
> +  <profile-toolbar [pageName]="'Editar Perfil'"></profile-toolbar>
Não precisa de data binding pra string

2021-07-10 18:15 UTC, ricklemos commented on src/app/profile/containers/profile-edit-page/profile-edit-page.component.scss
> +  height: 100vh;
% ou px

2021-07-10 18:15 UTC, ricklemos commented on src/app/profile/containers/profile-edit-page/profile-edit-page.component.scss
> +.profilepagecontainer {
profile-page-container (boas práticas de nomenclatura)

2021-07-10 18:16 UTC, ricklemos commented on src/app/profile/containers/profile-view-page/profile-view-page.component.html
> +  <profile-toolbar [pageName]="'Perfil'"></profile-toolbar>
Tirar o data binding

2021-07-10 18:16 UTC, ricklemos commented on src/app/profile/containers/profile-view-page/profile-view-page.component.scss
> +.profilepagecontainer {
Código repetido

2021-07-10 18:16 UTC, ricklemos commented on src/app/profile/layout/layout-profile.component.ts
> +  // tslint:disable-next-line:component-selector
AAaaaaaacho que não precisa desse comentário. Confirma comigo depois

2021-07-10 18:17 UTC, ricklemos commented on src/app/profile/services/modify-user-data.service.ts
> +
O que é esse código todo comentado?

2021-07-10 18:17 UTC, ricklemos commented on src/app/profile/services/modify-user-data.service.ts
> +    this.angularFireAuth.authState.subscribe((user) => {
Tem que dar unsubscribe nesse cara no ngOnDestroy

2021-07-10 18:18 UTC, ricklemos commented on src/app/services/url.service.ts
> +  public getEditUrl(): string{
Deixa o nome do módulo no nome da função. Ex:
getProfileEditUrl()

2021-07-10 18:20 UTC, ricklemos requested changes

2021-07-10 18:20 UTC, ricklemos commented on src/app/profile/components/change-password/change-password.component.scss
> +.text {
text, text2, text3 não é uma boa prática pra hierarquizar os textos. Tenta descrever melhor o que são os textos

2021-07-10 18:23 UTC, priveras01 approved these changes

2021-07-10 18:23 UTC, gabrielmd96 commented on src/app/profile/services/modify-user-data.service.ts
> +  // editFirstName(newFirstName: string): void {
só falta apagar o código comentado

2021-07-10 18:24 UTC, priveras01 approved these changes

2021-07-10 18:26 UTC, gabrielmd96 approved these changes

2021-07-12 17:10 UTC, gabrielmd96 commented on src/app/profile/components/profile-toolbar/profile-toolbar.component.scss
> +  width: 100vw;
se funcionar com % acho válido. mas não vejo problema em usar o vw pro header

2021-07-12 17:12 UTC, gabrielmd96 commented on src/app/profile/containers/change-password-page/change-password-page.component.scss
> +  height: 100vh;
não sei se o % funciona nesse caso, pq se não tiver itens suficientes no container ele não vai ficar do tamanho da página, o que pode atrapalhar a cor do background. ou eu tô chorumando?

2021-07-12 22:55 UTC, ricklemos approved these changes

2021-07-12 23:05 UTC, merged