Feat profile pic
ricklemos/sabia-appuser pull request #14
Opened 2021-07-12 22:48 UTC by gabrielmd96

A melhor PR que eu já fiz (modéstia à parte).
Falta fazer o dialog de excluir a foto

2021-07-12 23:01 UTC, ricklemos requested changes

2021-07-12 23:01 UTC, ricklemos commented on src/app/profile/components/profile-view/profile-view.component.ts
> +  updatePic(event): void {
Esse código ta repetido. Talvez seja o caso de fazer um service pra isso

2021-07-12 23:03 UTC, ricklemos approved these changes

2021-07-14 21:04 UTC, NandaParodi approved these changes

2021-07-15 00:11 UTC, priveras01 approved these changes

2021-07-15 00:13 UTC, merged