Feat questionary
ricklemos/sabia-appuser pull request #16
Opened 2021-07-23 17:30 UTC by gabrielmd96

**O que foi feito:**
Montei toda a estrutura de exercícios, ou seja:
- Tela de visualização da trilha (pega das lições do moduleProgress)
- Fluxo do questionário (pega do questionaryAnswers e o atualiza após respostas).
- Regras de segurança (para acessar, o usuário deve estar logado e ele só consegue acesso que for o dono) (código no firebase)
- Feedback das questões (essa era a task do Rick, fizemos juntos na quinta 22/07)
**Algumas pendências para melhorar depois:**
- Alterar tema padrão do MaterialDesign (deixar a barra de progresso com a cor do app)
- Criar uma Cloud Function no Firebase para atualizar o progresso do módulo quando o usuário conclui um questionário (no momento isso está no front).
- Barra de navegação do topo (não tem barra no topo na visualização de trilha). Eu ainda não fiz porque acredito que seja um componente global. Queria ver com vocês como fazer da melhor forma.
- Linha de conexão da trilha: um detalhe estético que eu não faço ideia de como fazer no front agora, deixei pra depois.

Qualquer dúvida, comentem no código aqui, mandem áudio etc!

2021-07-26 21:51 UTC, priveras01 approved these changes

2021-07-26 22:25 UTC, NandaParodi approved these changes

2021-07-26 22:25 UTC, NandaParodi commented on src/app/profile/components/profile-pic/profile-pic.component.ts
> -import { Component, Input, OnDestroy, OnInit } from '@angular/core';
Não tem OnDestroy mesmo?

2021-07-27 18:34 UTC, ricklemos requested changes

2021-07-27 18:34 UTC, ricklemos commented on src/app/module/layout/layout-module/layout-module.component.ts
> +  // tslint:disable-next-line:component-selector
Acho que não precisa desse tslint aqui. Confirma se dá erro

2021-07-27 18:34 UTC, ricklemos commented on src/app/module/models/module.ts
> +  // TODO: adicionar outros tipos de lição
Por enquanto, pode tirar esse TODO

2021-07-27 18:34 UTC, ricklemos commented on src/app/module/models/module.ts
> +  questionary?: string; // questionary reference ou questionary id? -> por enquanto está sendo usado o Id
Mudar isso pra questionaryId acho que é melhor (precisamos conversar pra mudar no db também

2021-07-27 18:34 UTC, ricklemos commented on src/app/questionary/components/questionary-done/questionary-done.component.ts
> +      const nLessons = module.lessons.length;
Por padrão, evite usar mais de um nível numa variável. Exemplo:
variável.nivel1.nivel2

2021-07-27 18:34 UTC, ricklemos commented on src/app/questionary/layout/layout-questionary/layout-questionary.component.ts
> +  // tslint:disable-next-line:component-selector
Checar se dá erro se tirar

2021-07-27 18:34 UTC, ricklemos commented on src/app/sessions/containers/sessions-logged-page/sessions-logged-page.component.ts
já coloca o moduleId como parâmetro, quando chamar essa função, aí sim você passa o 0001

2021-07-27 18:42 UTC, gabrielmd96 commented on src/app/module/models/module.ts
> +  // TODO: adicionar outros tipos de lição
ok!

2021-07-27 18:43 UTC, gabrielmd96 commented on src/app/module/models/module.ts
> +  questionary?: string; // questionary reference ou questionary id? -> por enquanto está sendo usado o Id
Concordo, vou alterar!

2021-07-27 18:44 UTC, gabrielmd96 commented on src/app/questionary/components/questionary-done/questionary-done.component.ts
> +      const nLessons = module.lessons.length;
Aqui deveria ter uma variavel "Lessons" primeiro, então? e aí ficaria const nLessons = lessons.length?

2021-07-27 18:45 UTC, gabrielmd96 commented on src/app/questionary/layout/layout-questionary/layout-questionary.component.ts
> +  // tslint:disable-next-line:component-selector
Se tirar o que? a linha de comentário?

2021-07-29 14:09 UTC, gabrielmd96 commented on src/app/profile/components/profile-pic/profile-pic.component.ts
> -import { Component, Input, OnDestroy, OnInit } from '@angular/core';
Acho que não, pq em tese, quando o componente é destruído, a variável também é

2021-07-29 14:15 UTC, gabrielmd96 commented on src/app/questionary/components/questionary-done/questionary-done.component.ts
> +      const nLessons = module.lessons.length;
Esse código vai virar uma cloud function, então vou deixar assim, beleuza?

2021-07-29 14:15 UTC, gabrielmd96 commented on src/app/sessions/containers/sessions-logged-page/sessions-logged-page.component.ts
Isso aqui vai sumir tudo quando a gente fizer a home direito, acho que nem faz sentido ter uma página chamada "sessionsLogged"

2021-08-04 19:39 UTC, ricklemos commented on src/app/questionary/components/questionary-done/questionary-done.component.ts
> +      const nLessons = module.lessons.length;
Não esquece de usar destructuring
`const { lessons} = module;`

2021-08-04 19:42 UTC, ricklemos approved these changes

2021-08-04 20:13 UTC, merged