Feat module track
ricklemos/sabia-appuser pull request #17
Opened 2021-08-04 21:49 UTC by gabrielmd96

[https://dev.azure.com/tcc-fpgr/mvp1-scrum/_sprints/taskboard/mvp1-scrum%20Team/mvp1-scrum/Sprint%205](PBI na Azure)

2021-08-06 00:35 UTC, NandaParodi approved these changes

2021-08-09 20:00 UTC, ricklemos requested changes

2021-08-09 20:00 UTC, ricklemos commented on src/app/module/components/module-body/module-body.component.html
> +      <label [for]="lesson.lessonName">
Não entendi porque o uso de label

2021-08-09 20:00 UTC, ricklemos commented on src/app/module/components/module-body/module-body.component.html
> +      <button [id]="lesson.lessonName" hidden (click)="startLesson(lesson)"></button>
Pq você ta passando o id pro botão? E pq hidden?

2021-08-09 20:00 UTC, ricklemos commented on src/app/module/components/module-body/module-body.component.ts
> +    this.loading = true;
Ao invés de constatar isso no constructor, você pode instanciar já como true. Na linha 18:
`loading = true;`

2021-08-09 20:00 UTC, ricklemos commented on src/app/module/components/module-body/module-body.component.ts
> +        this.loading = false;
Se der errado, vai ficar em loading infinito. Tem que prever caso de erro.
Ver https://www.learnrxjs.io/learn-rxjs/operators/error_handling/catch

2021-08-09 20:03 UTC, gabrielmd96 commented on src/app/module/components/module-body/module-body.component.html
> +      <label [for]="lesson.lessonName">
Pro botão funcionar tanto no ícone, quanto no texto. Existe uma forma melhor de fazer?

2021-08-09 20:04 UTC, gabrielmd96 commented on src/app/module/components/module-body/module-body.component.html
> +      <button [id]="lesson.lessonName" hidden (click)="startLesson(lesson)"></button>
Mesmo do item acima.

2021-08-18 13:27 UTC, ricklemos requested changes

2021-08-18 13:27 UTC, ricklemos commented on src/app/module/components/module-body/module-body.component.html
> +      <label [for]="lesson.lessonName">
Mas ainda ta label aqui

2021-08-18 14:08 UTC, priveras01 approved these changes

2021-08-18 16:54 UTC, ricklemos approved these changes

2021-08-18 16:57 UTC, merged