feat: questionary review page
ricklemos/sabia-appuser pull request #19
Opened 2021-08-12 22:03 UTC by NandaParodi

2021-08-16 11:31 UTC, gabrielmd96 approved these changes
Sucesso demais, Fer!

2021-08-18 13:34 UTC, ricklemos requested changes

2021-08-18 13:34 UTC, ricklemos commented on src/app/questionary/containers/questionary-review-page/questionary-review-page.component.html
> +  <button clButtonContainedSecondary class="bg-sabia-blue-force" (click)="redoTest()">REFAZER O QUIZZ</button>
Botões sempr com a grafia:
Refazer o quizz

(Só a primeira letra maiúscula)

2021-08-18 13:34 UTC, ricklemos commented on src/app/questionary/containers/questionary-review-page/questionary-review-page.component.ts
> +    console.log(this.questionaryId);
Console.log

2021-08-18 13:34 UTC, ricklemos commented on src/app/questionary/containers/questionary-review-page/questionary-review-page.component.ts
> +        this.questions = questionary.questions;
Porque tem mais uma variável questions se ela já ta dentro da variável questionary?
De duas uma:
1) Nem sempre vai ter questions dentro de questionary: aí você tem que fazer verificação.
`this.questionary = questionary
if (this.questionary && this.questionary.questions) {
    this.questions = this.questionary.questions
}`

2) Sempre vai ter. Então ao invés de usar this.questions, pode usar this.questionary.questions

2021-08-18 13:34 UTC, ricklemos commented on src/app/questionary/containers/questionary-review-page/questionary-review-page.component.ts
> +        this.questions = questionary.questions;
Ficou péssima a formatação do código, sry

2021-08-18 14:04 UTC, priveras01 approved these changes

2021-08-20 01:13 UTC, ricklemos approved these changes

2021-08-21 15:53 UTC, merged