Feat layout cursos
ricklemos/sabia-appuser pull request #20
Opened 2021-08-22 15:31 UTC by priveras01

2021-08-22 15:39 UTC, gabrielmd96 commented on src/app/courses/services/courses.service.ts
> +    // TODO: revisar essa funçao (sera feito apos um merge em develop)
Isso aqui não é mais um todo, tá feito!

2021-08-22 15:40 UTC, gabrielmd96 approved these changes

2021-08-22 16:00 UTC, NandaParodi commented on src/app/courses/services/courses.service.ts
> +    // tslint:disable-next-line:max-line-length
Pq esse código comentado aqui? Não é necessário? Se não acho que pode deletar

2021-08-22 16:01 UTC, NandaParodi approved these changes

2021-08-23 15:45 UTC, ricklemos requested changes

2021-08-23 15:45 UTC, ricklemos commented on src/app/courses/components/courses-module-box/courses-module-box.component.scss
> +  width: 60%;
De onde veio esse 60%? Use medidas fixas (px)

2021-08-23 15:45 UTC, ricklemos commented on src/app/courses/components/courses-module-box/courses-module-box.component.scss
> +  width: 60%;
No desktop isso vira aberração

2021-08-23 15:45 UTC, ricklemos commented on src/app/courses/containers/courses-course-details-page/courses-course-details-page.component.ts
> +    ).subscribe(noop);
Não ta dando unsubscribe nisso

2021-08-23 15:45 UTC, ricklemos commented on src/app/courses/containers/courses-mycourses-page/courses-mycourses-page.component.ts
> +    ).subscribe(noop);
Não ta dando unsubscribe nisso

2021-08-23 15:45 UTC, ricklemos commented on src/app/courses/courses-routing.module.ts
> +    // canActivate: [AuthGuard]
Ligar de volta esse Guard

2021-08-23 15:45 UTC, ricklemos commented on src/app/courses/services/courses.service.ts
> +    // tslint:disable-next-line:max-line-length
Isso é pra não mostrar a linha de baixo como erro. Não é bem um comentário, é um comando do tslint.
De qualquer forma, quebra a linha de baixo que esse problema vai embora

2021-08-23 15:45 UTC, ricklemos commented on src/app/courses/services/courses.service.ts
> +    // tslint:disable-next-line:max-line-length
Recomendo logo antes do .where

2021-08-23 23:09 UTC, priveras01 commented on src/app/courses/services/courses.service.ts
> +    // TODO: revisar essa funçao (sera feito apos um merge em develop)
Corrigido!

2021-08-23 23:09 UTC, priveras01 commented on src/app/courses/services/courses.service.ts
> +    // tslint:disable-next-line:max-line-length
corrigido!

2021-08-23 23:18 UTC, priveras01 commented on src/app/courses/components/courses-module-box/courses-module-box.component.scss
> +  width: 60%;
corrigido!

2021-08-23 23:35 UTC, priveras01 commented on src/app/courses/containers/courses-course-details-page/courses-course-details-page.component.ts
> +    ).subscribe(noop);
corrigido!

2021-08-23 23:35 UTC, priveras01 commented on src/app/courses/containers/courses-mycourses-page/courses-mycourses-page.component.ts
> +    ).subscribe(noop);
corrigido!

2021-08-23 23:36 UTC, priveras01 commented on src/app/courses/courses-routing.module.ts
> +    // canActivate: [AuthGuard]
corrigido

2021-08-26 19:39 UTC, ricklemos approved these changes

2021-08-26 19:57 UTC, merged