Feat rankings layout
ricklemos/sabia-appuser pull request #21
Opened 2021-08-23 00:50 UTC by NandaParodi

2021-08-23 13:38 UTC, gabrielmd96 approved these changes

2021-08-23 15:41 UTC, ricklemos requested changes

2021-08-23 15:41 UTC, ricklemos commented on src/app/rankings/components/ranking-user-data/ranking-user-data.component.html
> +<div *ngIf="itsMe" class="itsMeDiv">
Não entendi porque você ta fazendo duas vezes as tres melhores posições. Você pode explorar um negócio cahamado [ngClass]
Nele você consegue passar uma classe como variável:
[ngClass] ="profileClass"

No ts você faz toda a lógica para decidir qual(is) será(ão) a(s) class(s):
itsMe? Então a classe vai ser this.profileClass="itsMe"
É ouro? Então a classe vai ser this.profileClass = this.profileClass + 'position__gold'
É prata? Então a classe vai ser this.profileClass = this.profileClass + 'position__silver'

2021-08-23 15:41 UTC, ricklemos commented on src/app/rankings/components/ranking-user-data/ranking-user-data.component.html
> +<div *ngIf="itsMe" class="itsMeDiv">
Com isso você evita código repetido

2021-08-23 15:41 UTC, ricklemos commented on src/app/profile/components/profile-pic/profile-pic.component.html
> -<img [src]="pictureLink | async" onerror="this.src='./../../../assets/img/profile-pic-std.png'">
Não entendi a necessidade de fazer um componente só para a foto

2021-08-23 15:41 UTC, ricklemos commented on src/app/rankings/components/ranking-user-data/ranking-user-data.component.scss
> +  background-color: rgba(0,0,0,0.1);
backgroundColor = $black-alpha-100

2021-08-23 15:41 UTC, ricklemos commented on src/app/rankings/components/ranking-user-data/ranking-user-data.component.scss
> +  background-color: rgba(0,0,0,0.1);
ou 200, o que ficar melhor

2021-08-23 15:41 UTC, ricklemos commented on src/app/rankings/containers/rankings-class-page/rankings-class-page.component.html
> +<div fxLayout="column" fxLayoutGap="16px" style="padding: 16px">
style in line não pf.
Cria uma classe pra esse cara

2021-08-23 15:41 UTC, ricklemos commented on src/app/rankings/containers/rankings-page/rankings-page.component.html
> +<div fxLayout="column" fxLayoutGap="16px" style="padding: 16px">
Style inline

2021-08-23 15:41 UTC, ricklemos commented on src/app/rankings/containers/rankings-page/rankings-page.component.html
> +  <div *ngFor="let enrollment of enrollments"><!--    ngfor-->
Comentário solto

2021-08-23 15:41 UTC, ricklemos commented on src/app/rankings/containers/rankings-page/rankings-page.component.ts
> +    ).subscribe(noop);
Você não ta dando unsubscribe nesse cara

2021-08-23 15:41 UTC, ricklemos commented on src/app/rankings/services/ranking-class.service.ts
> +    private afs: AngularFirestore,
Shift+F6
angularFirestore

2021-08-23 23:56 UTC, priveras01 approved these changes

2021-08-26 19:41 UTC, ricklemos approved these changes

2021-08-26 22:10 UTC, merged