Feat upload classroom
ricklemos/sabia-appuser pull request #24
Opened 2021-09-06 20:01 UTC by gabrielmd96

Agora é possível criar uma classe no front a partir de um "courseTemplate" do banco de dados. É possível subir um CSV com o e-mail dos alunos para adicioná-los na turma, inclusive se a turma já existe. 

[História associada](https://dev.azure.com/tcc-fpgr/mvp1-scrum/_sprints/taskboard/mvp1-scrum%20Team/mvp1-scrum/Sprint%206?workitem=134)

Obs: ESTA FEATURE ESTÁ ABERTA NO FRONT! isso significa que qualquer usuário pode fazer isso. Ainda precisamos verificar como separar os papéis de 'admin' e 'aluno' usando o [firebase](https://firebase.google.com/docs/auth/admin/custom-claims).

2021-09-08 22:18 UTC, priveras01 approved these changes

2021-09-11 23:01 UTC, NandaParodi commented on functions/src/create-enrollments.ts
> +                  .catch(err => console.log('erro:', err));
Minha primeira vez de polícia do console log (a não ser que no erro faça sentido manter)

2021-09-11 23:01 UTC, NandaParodi commented on functions/src/create-enrollments.ts
> +            }).catch((err) => console.log('erro:', err));
Aqui também

2021-09-11 23:01 UTC, NandaParodi commented on functions/src/tests.ts
> +    const users = [
Esses dados todos feitos "na mão" não precisam ser substituidos?

2021-09-11 23:01 UTC, NandaParodi commented on src/app/instructor-dash/instructor-dash-routing.module.ts
> +        // canActivate: [AuthGuard]
Pq comentado?

2021-09-11 23:16 UTC, gabrielmd96 commented on functions/src/create-enrollments.ts
> +                  .catch(err => console.log('erro:', err));
hauahuah também não sei. eu deixei pq é erro. @ricklemos

2021-09-11 23:17 UTC, gabrielmd96 commented on functions/src/tests.ts
> +    const users = [
Sim! essa função é só pra automatizar os testes e o upload. Elas podem ser úteis pra gente subir os dados depois no banco de dados oficial de uma vez só!

2021-09-11 23:18 UTC, gabrielmd96 commented on src/app/instructor-dash/instructor-dash-routing.module.ts
> +        // canActivate: [AuthGuard]
pq eu esqueci de descomentar :) vou corrigir

2021-09-12 17:19 UTC, ricklemos requested changes

2021-09-12 17:19 UTC, ricklemos commented on src/app/instructor-dash/components/create-classroom-form/create-classroom-form.component.ts
> +  formCourse: ClFieldConfig[] = [
É bom colocar esse cara em outro arquivo, podemos ver isso juntos

2021-09-12 17:19 UTC, ricklemos commented on src/app/instructor-dash/instructor-dash-routing.module.ts
> +            path: 'create',
pt-br

2021-09-12 17:19 UTC, ricklemos commented on src/app/services/url.service.ts
> +    return `/instructor/classrooms`;
pt-br

2021-09-12 17:19 UTC, ricklemos commented on src/app/services/url.service.ts
> +    return `/instructor/classrooms/${ classroomId }`;
pt-br

2021-09-12 17:19 UTC, ricklemos commented on src/app/app-routing.module.ts
> +    path: 'instructor',
pt-br

2021-09-12 17:19 UTC, ricklemos commented on src/app/instructor-dash/components/students-form/students-form.component.scss
> +@import "/src/assets/styles/instructor-dash";
Dá pra deletar esse arquivo e só importar esse CSS direto no ts

2021-09-12 17:19 UTC, ricklemos commented on src/app/instructor-dash/containers/classroom-page/classroom-page.component.scss
> +@import "/src/assets/styles/instructor-dash";
Mesma coisa aqui

2021-09-12 17:19 UTC, ricklemos commented on src/app/instructor-dash/containers/classrooms-page/classrooms-page.component.scss
> +@import "/src/assets/styles/instructor-dash";
rt (2)

2021-09-12 17:19 UTC, ricklemos commented on src/app/instructor-dash/containers/create-new-classroom-page/create-new-classroom-page.component.scss
> +@import "/src/assets/styles/instructor-dash";
rt (3)

2021-09-12 17:53 UTC, ricklemos approved these changes

2021-09-12 17:54 UTC, merged