Feat roles
ricklemos/sabia-appuser pull request #25
Opened 2021-09-08 23:26 UTC by gabrielmd96

Agora temos papéis!  

é possível editar os papeis dos usuários se você logar como um usuário master. 

Falta editar as páginas "home" específicas para cada role. Assim que tivermos isso pronto, mandamos.

2021-09-09 12:37 UTC, NandaParodi approved these changes

2021-09-09 18:56 UTC, priveras01 approved these changes

2021-09-12 17:27 UTC, ricklemos requested changes

2021-09-12 17:27 UTC, ricklemos commented on src/app/instructor-dash/instructor-dash-routing.module.ts
> +        // canActivate: [AuthGuard]
Não é bom deixar o AuthGuard?

2021-09-12 17:27 UTC, ricklemos commented on src/app/instructor-dash/components/create-classroom-form/create-classroom-form.component.ts
> +  formCourse: ClFieldConfig[] = [
É uma boa colocar esse cara em outro arquivo. Podemos ver juntos

2021-09-12 17:27 UTC, ricklemos commented on src/app/instructor-dash/containers/classroom-page/classroom-page.component.scss
> +@import "/src/assets/styles/instructor-dash";
importar esse cara direto no ts

2021-09-12 17:27 UTC, ricklemos commented on src/app/instructor-dash/containers/classrooms-page/classrooms-page.component.scss
> +@import "/src/assets/styles/instructor-dash";
importar no ts

2021-09-12 17:27 UTC, ricklemos commented on src/app/instructor-dash/containers/create-new-classroom-page/create-new-classroom-page.component.scss
> +@import "/src/assets/styles/instructor-dash";
importar no ts

2021-09-12 17:27 UTC, ricklemos commented on src/app/instructor-dash/components/create-classroom-form/create-classroom-form.component.scss
> +@import "/src/assets/styles/instructor-dash";
importa no ts

2021-09-12 17:27 UTC, ricklemos commented on src/app/instructor-dash/components/create-classroom-form/create-classroom-form.component.ts
> +  selector: 'create-classroom-form',
nomenclatura

2021-09-12 17:27 UTC, ricklemos commented on src/app/instructor-dash/components/students-form/students-form.component.scss
> +@import "/src/assets/styles/instructor-dash";
importar no ts

2021-09-12 17:27 UTC, ricklemos commented on src/app/instructor-dash/components/students-form/students-form.component.ts
> +  selector: 'students-form',
nomenclatura

2021-09-12 17:27 UTC, ricklemos commented on src/app/instructor-dash/containers/classroom-page/classroom-page.component.ts
> +  selector: 'classroom-page',
nomentclatura

2021-09-12 17:27 UTC, ricklemos commented on src/app/sessions/containers/sessions-edit-role-page/sessions-edit-role-page.component.ts
> +  form: ClFieldConfig[] = [
Vamos colocar esse cara em outro arquivo

2021-09-12 20:29 UTC, ricklemos approved these changes

2021-09-12 20:33 UTC, merged