Feat navbar
ricklemos/sabia-appuser pull request #26
Opened 2021-09-11 14:23 UTC by ricklemos

2021-09-11 14:55 UTC, gabrielmd96 commented on src/app/navigation/navbar-header/navbar-header.component.ts
> +        this.pictureLink = picture;
era só usar o componente de profile-pic, eu acho. não precisava fazer essa lógica de novo

2021-09-11 14:56 UTC, gabrielmd96 approved these changes

2021-09-11 22:48 UTC, NandaParodi requested changes

2021-09-11 22:48 UTC, NandaParodi commented on src/app/sessions/containers/sessions-logged-page/sessions-logged-page.component.html
> +<navbar barTitle="Início">
Precisa ter um botão para voltar para a home também

2021-09-12 18:20 UTC, ricklemos commented on src/app/sessions/containers/sessions-logged-page/sessions-logged-page.component.html
> +<navbar barTitle="Início">
Ele existe, tem um jeito de colocar ele que eu mostro pra vocês

2021-09-12 20:21 UTC, priveras01 approved these changes

2021-09-12 20:21 UTC, NandaParodi approved these changes

2021-09-12 20:35 UTC, merged