Feat home
ricklemos/sabia-appuser pull request #27
Opened 2021-09-11 22:44 UTC by NandaParodi

2021-09-11 23:10 UTC, gabrielmd96 commented on src/app/home/components/home-module/home-module.component.html
> +        [colors]="lineChartColors"
só pra não fugir do padrão, em tese aqui deveria ser "pieChartColors"

2021-09-11 23:14 UTC, gabrielmd96 commented on src/app/home/home-routing.module.ts
> +        path: '1',
estranho só ter funcionado assim, mas ok

2021-09-11 23:15 UTC, gabrielmd96 commented on src/app/home/home.module.ts
> +  providers: [],
aqui também falta declarar o provider HomeService, eu acho (apesar dele funcionar sem essa declaração)

2021-09-11 23:15 UTC, gabrielmd96 approved these changes

2021-09-12 17:08 UTC, ricklemos requested changes

2021-09-12 17:08 UTC, ricklemos commented on src/app/home/components/recent-modules/recent-modules.component.ts
> +  selector: 'recent-modules',
Nomenclatura

2021-09-12 17:08 UTC, ricklemos commented on src/app/home/components/start-now/start-now.component.ts
> +  selector: 'start-now',
Nomenclatura

2021-09-12 17:08 UTC, ricklemos commented on src/app/home/home-routing.module.ts
> +        path: '1',
Porque isso?

2021-09-12 17:08 UTC, ricklemos commented on src/app/home/home-routing.module.ts
> +        path: '1',
Na minha cabeça a Home vai substituir a sessions-logged. Então não precisa de path. A gente pode ver juntos

2021-09-12 18:12 UTC, ricklemos approved these changes

2021-09-12 19:14 UTC, priveras01 approved these changes

2021-09-12 19:17 UTC, merged