Feat update module progress percentage cloud function
ricklemos/sabia-appuser pull request #33
Opened 2021-09-16 19:31 UTC by gabrielmd96

2021-09-16 20:11 UTC, priveras01 approved these changes

2021-09-18 18:17 UTC, NandaParodi approved these changes

2021-09-18 18:47 UTC, ricklemos requested changes

2021-09-18 18:47 UTC, ricklemos commented on functions/src/models.ts
> +  lessonType: 'TEXT' | 'QUESTIONNAIRE' | 'QUESTIONARY';
Pq QUESTIONNAIRE e QUESTIONARY? Não seria só um deles?

2021-09-18 20:15 UTC, merged