fix: add courseDescription and courseLink as mandatory
ricklemos/sabia-appuser pull request #34
Opened 2021-09-20 19:23 UTC by gabrielmd96

adicionei agora para a turma e para o curso a obrigatoriedade de colocar os campos "courseDescription" e "courseLink". Se não tiver esses campos, as cloud functions não conseguem criar os outros documentos.

2021-09-20 22:47 UTC, priveras01 approved these changes

2021-09-20 23:19 UTC, NandaParodi approved these changes

2021-09-21 22:40 UTC, ricklemos requested changes

2021-09-21 22:40 UTC, ricklemos commented on src/assets/styles/sessions.style.scss
> +//@import "theming";
Arranca fora

2021-09-22 23:51 UTC, merged