Release v0.1
ricklemos/sabia-appuser pull request #35
Opened 2021-09-28 23:08 UTC by gabrielmd96

VAMO PORRA

2021-10-01 21:13 UTC, priveras01 approved these changes

2021-10-08 12:52 UTC, ricklemos requested changes

2021-10-08 12:52 UTC, ricklemos commented on functions/src/index.ts
> +// import * as tests from './tests';
Arranca os comentários

2021-10-08 12:52 UTC, ricklemos commented on functions/src/index.ts
> +// export const createMockupData = tests.createMockupData;
Aqui também

2021-10-08 12:52 UTC, ricklemos commented on src/app/guards/auth.guard.ts
> +  // async canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Promise<boolean | UrlTree> {
Se não ta usando, ranca fora

2021-10-08 12:52 UTC, ricklemos commented on src/app/welcome/welcome-routing.module.ts
> +        path: '1',
Não é melhor só deixar ''?

2021-10-08 12:52 UTC, ricklemos commented on src/app/welcome/components/welcome-course-box/welcome-course-box.component.ts
> +export class WelcomeCourseBoxComponent implements OnInit {
PAREM DE CHAMAR AS COISAS DE BOX

2021-10-08 13:09 UTC, gabrielmd96 commented on src/app/welcome/components/welcome-course-box/welcome-course-box.component.ts
> +export class WelcomeCourseBoxComponent implements OnInit {
verdade, vou chamar de caixa

2021-10-08 13:09 UTC, gabrielmd96 commented on src/app/welcome/welcome-routing.module.ts
> +        path: '1',
não tava funcionando :( isso me dá um desespero hauhauh

2021-10-08 13:09 UTC, eng-gabs commented on src/app/guards/auth.guard.ts
> +  // async canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Promise<boolean | UrlTree> {
beleza!

2021-10-08 16:40 UTC, NandaParodi approved these changes

2021-10-08 20:45 UTC, merged