Feat stocks service
ricklemos/sabia-appuser pull request #40
Opened 2021-10-28 12:50 UTC by gabrielmd96

2021-10-28 12:56 UTC, ricklemos requested changes

2021-10-28 12:56 UTC, ricklemos commented on src/app/services/stocks.service.ts
> +  fetchStockByTicker(ticker: string): Observable<any>{
Esse cara não é Promise?

2021-10-28 18:59 UTC, eng-gabs commented on src/app/services/stocks.service.ts
> +  fetchStockByTicker(ticker: string): Observable<any>{
é Observable pq se o valor alterar ele atualiza

2021-11-01 16:07 UTC, ricklemos approved these changes

2021-11-01 18:08 UTC, NandaParodi approved these changes

2021-11-01 22:24 UTC, priveras01 approved these changes

2021-11-06 19:12 UTC, merged