feat: wallet services
ricklemos/sabia-appuser pull request #43
Opened 2021-11-01 22:03 UTC by NandaParodi

Serviços de compra e vendas de ações, além de cálculo do rendimento de uma ação presente na carteira do usuário.

2021-11-01 22:36 UTC, priveras01 approved these changes

2021-11-03 13:37 UTC, gabrielmd96 approved these changes
Pra mim tá tudo check. Quero ver ao vivo! hauhauha

2021-11-06 18:28 UTC, ricklemos requested changes
Dá um rebase na branch

2021-11-08 22:27 UTC, priveras01 approved these changes

2021-11-17 19:29 UTC, ricklemos approved these changes

2021-11-17 19:30 UTC, merged