feat: created sessions models to match firebase database
ricklemos/sabia-appuser pull request #9
Opened 2021-06-25 19:16 UTC by gabrielmd96

2021-06-25 22:03 UTC, NandaParodi approved these changes

2021-06-30 16:39 UTC, priveras01 approved these changes

2021-07-09 18:11 UTC, ricklemos requested changes

2021-07-09 18:11 UTC, ricklemos commented on src/app/sessions/models/sessions-user-data.ts
> +export interface SessionsUserData {
Não precisa criar um arquivo pra cada interface. Cria um arquivo geral tipo sessions-models.ts

2021-07-09 18:11 UTC, ricklemos commented on src/app/sessions/models/sessions-user.ts
> +export interface SessionsUser {
Criou mas não usou

2021-07-09 18:18 UTC, gabrielmd96 commented on src/app/sessions/models/sessions-user-data.ts
> +export interface SessionsUserData {
blz

2021-07-09 18:18 UTC, gabrielmd96 commented on src/app/sessions/models/sessions-user.ts
> +export interface SessionsUser {
sim, é pra vocês usarem

2021-07-09 19:08 UTC, merged